# Part 1 - reading the iris data set

First we read in the data. We can do everything with the training set, X_train and y_train. X_test and y_test should be handled with care. 

In [1]:
import numpy as np

# We use the same functions as shown in exercise 2
X_train = np.loadtxt('iris_train.data', delimiter=' ', dtype=float)
y_train = np.loadtxt('iris_train.labels', dtype=int)
X_test = np.loadtxt('iris_test.data', delimiter=' ', dtype=float)
y_test = np.loadtxt('iris_test.labels', delimiter=' ', dtype=float)

# Part 2 - classifying the data

Build a classifier and see how it works on the training data. 

In [2]:
import random

def classify(x):
    """Classify a single data point."""
    if x[0] < 6 and x[3] < 0.6:
        return 0
    elif x[0] > 4.75 and x[0] < 7.1 and x[3] > 0.75 and x[3] < 1.75:
        return 1
    else: 
        return 2

In [3]:
# X_train is a 2d numpy.ndarray
print('X_train type: %s, shape: %s' % (type(X_train), X_train.shape))
# Each element (row) of X_train is ad numpy.ndarray describing one observation
print('x type: %s, shape: %s' % (type(X_train[0]), X_train[0].shape))
# y_train is a 1d numpy.ndarray; each value is the target value for one observation
print('y_train type: %s, shape %s' % (type(y_train), y_train.shape))

# A list for our predictions
y_hat = []

for x in X_train:
    y_hat.append(classify(x))
    
# Output our predictions
print('Predictions:', y_hat)

# Calculate the training error
errors = 0
for y_true, y_pred in zip(y_train, y_hat):
    if y_true != y_pred:
        errors += 1
        
training_error = errors / len(X_train) * 100
print('Training error is %g percent.' % training_error)

X_train type: <class 'numpy.ndarray'>, shape: (100, 4)
x type: <class 'numpy.ndarray'>, shape: (4,)
y_train type: <class 'numpy.ndarray'>, shape (100,)
Predictions: [0, 0, 2, 1, 0, 1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 0, 2, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 0, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 1, 2, 2, 2, 2, 1, 1]
Training error is 2 percent.


# Part 3 - test the classifier on unseen data

Once you are happy with your classifier, you can test it on the hidden test set. Make sure that you know what the implications are. 

In [4]:
# A list for our predictions
y_hat = []

for x in X_test:
    y_hat.append(classify(x))
    
# Output our predictions
print('Predictions:', y_hat)

# Calculate the training error
errors = 0
for y_true, y_pred in zip(y_train, y_hat):
    if y_true != y_pred:
        errors += 1
        
test_error = errors / len(X_test) * 100
print('Test error is %g percent.' % test_error)

Predictions: [1, 0, 2, 1, 1, 2, 2, 0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 0, 2, 1, 2, 0, 1, 0, 1, 0, 2, 1, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 1, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0]
Test error is 64 percent.


Exercie 4.2 matrix multiplication

In [10]:
import numpy as np
a = np.array([[5,8],[2,1],[6,7]])
b= np.array([[5,8,3],[2,1,9]])
c = np.dot(a,b)
print(c)

[[41 48 87]
 [12 17 15]
 [44 55 81]]


Eigenvalues of matrix

In [14]:
from numpy import linalg as LA
d = np.array([[1,2],[2,4]])
w,v = LA.eig(d)
print(w)
print(v)

[ 0.  5.]
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
